name: Deploy production site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get vangen
        run: go get github.com/yzs981130/vangen
      - name: Update HTML
        run: vangen -out public
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}